version: '3.1'
services:
  test-node-server:
    image: test-ubuntu-jdk17-node
    command: sleep infinity

  test-node-agent:
    image: test-puppet-agent-node
    command: /opt/puppetlabs/bin/puppet resource service puppet ensure=running enable=true
