version: '3.8'

services:
  puppet:
    image: ghcr.io/voxpupuli/container-puppetserver:8.4.0-latest
    container_name: puppet-server-1
    hostname: puppet
    environment:
      PUPPETSERVER_HOSTNAME: puppet
      PUPPETSERVER_PORT: 8140
      USE_PUPPETDB: false
      AUTOSIGN: true
      CSR_ATTRIBUTES: '{"custom_attributes": { "challengePassword": "foobar" }, "extension_requests": { "pp_project": "foo" } }'
      # For private repos, use git@github.com:user/repo.git and provide SSH keys
      # R10K_REMOTE: https://github.com/betadots/demo-control-repo.git
    volumes:
      - puppetserver:/opt/puppetlabs/server/data/puppetserver
      - puppetserver-ssl:/etc/puppetlabs/puppet/ssl
      - puppetserver-ca:/etc/puppetlabs/puppetserver/ca
      - ./code/manifests:/etc/puppetlabs/code/environments/production/manifests
    restart: always
    ports:
      - 8140:8140
    deploy:
      resources:
        limits:
          memory: 2560M

networks:
  default:
    name: puppet-net

volumes:
  puppetserver:
  puppetserver-ssl:
  puppetserver-ca: